// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";

import { Plasmic学评总览快速体验 } from "../components/plasmic/base_demo/Plasmic\u5B66\u8BC4\u603B\u89C8\u5FEB\u901F\u4F53\u9A8C";

function 学评总览快速体验() {
  // Use Plasmic学评总览快速体验 to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into Plasmic学评总览快速体验 are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.

  return <Plasmic学评总览快速体验 />;
}

export default 学评总览快速体验;
