// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";

import { Plasmic学评点击模版开始创建 } from "../components/plasmic/base_demo/Plasmic\u5B66\u8BC4\u70B9\u51FB\u6A21\u7248\u5F00\u59CB\u521B\u5EFA";

function 学评点击模版开始创建() {
  // Use Plasmic学评点击模版开始创建 to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into Plasmic学评点击模版开始创建 are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.

  return <Plasmic学评点击模版开始创建 />;
}

export default 学评点击模版开始创建;
